version: '3'

services:

  # Database service for the blog app project
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: blogappdb
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    networks:
      - main

  # Web service for the blog app project
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - main
  
  # A database management tool 
  db_gui:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - main

networks:
  main: