# Generated by Django 2.0.4 on 2018-04-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20180426_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
