# Generated by Django 2.0.4 on 2018-05-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20180427_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('dateCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='blogCategory',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='blogOwner',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Blog_Category',
        ),
        migrations.DeleteModel(
            name='Blog_Post',
        ),
        migrations.DeleteModel(
            name='User_Account',
        ),
        migrations.DeleteModel(
            name='User_Information',
        ),
    ]
